/**
 * Tailwind reads from the token layer rather than carrying its own palette, so
 * `bg-tomato` and `var(--c-tomato)` are guaranteed to be the same colour.
 * @type {import('tailwindcss').Config}
 */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      cream: 'var(--c-cream)',
      'cream-deep': 'var(--c-cream-deep)',
      'cream-sunk': 'var(--c-cream-sunk)',
      line: 'var(--c-line)',
      'line-strong': 'var(--c-line-strong)',
      charcoal: 'var(--c-charcoal)',
      'ink-soft': 'var(--c-ink-soft)',
      'ink-faint': 'var(--c-ink-faint)',
      tomato: 'var(--c-tomato)',
      'tomato-ink': 'var(--c-tomato-ink)',
      'tomato-deep': 'var(--c-tomato-deep)',
      'tomato-wash': 'var(--c-tomato-wash)',
      sage: 'var(--c-sage)',
      'sage-ink': 'var(--c-sage-ink)',
      'sage-deep': 'var(--c-sage-deep)',
      'sage-wash': 'var(--c-sage-wash)',
      orange: 'var(--c-orange)',
      'orange-ink': 'var(--c-orange-ink)',
      'orange-wash': 'var(--c-orange-wash)',
      plum: 'var(--c-plum)',
      'plum-ink': 'var(--c-plum-ink)',
      'plum-wash': 'var(--c-plum-wash)',
      teal: 'var(--c-teal)',
      'teal-ink': 'var(--c-teal-ink)',
      'teal-wash': 'var(--c-teal-wash)',
      mustard: 'var(--c-mustard)',
      'mustard-ink': 'var(--c-mustard-ink)',
      'mustard-wash': 'var(--c-mustard-wash)',
      focus: 'var(--c-focus)',
      danger: 'var(--c-danger)',
      warning: 'var(--c-warning)',
      success: 'var(--c-success)',
    },
    spacing: {
      0: '0px',
      1: 'var(--s-1)',
      2: 'var(--s-2)',
      3: 'var(--s-3)',
      4: 'var(--s-4)',
      5: 'var(--s-5)',
      6: 'var(--s-6)',
      7: 'var(--s-7)',
      8: 'var(--s-8)',
      9: 'var(--s-9)',
      px: '1px',
      full: '100%',
    },
    fontSize: {
      xs: 'var(--t-xs)',
      sm: 'var(--t-sm)',
      md: 'var(--t-md)',
      lg: 'var(--t-lg)',
      xl: 'var(--t-xl)',
      '2xl': 'var(--t-2xl)',
      '3xl': 'var(--t-3xl)',
      '4xl': 'var(--t-4xl)',
      '5xl': 'var(--t-5xl)',
    },
    borderRadius: {
      none: '0',
      xs: 'var(--r-xs)',
      sm: 'var(--r-sm)',
      md: 'var(--r-md)',
      lg: 'var(--r-lg)',
      chip: 'var(--r-chip)',
      blob: 'var(--r-blob)',
      full: '9999px',
    },
    boxShadow: {
      none: 'none',
      1: 'var(--e-1)',
      2: 'var(--e-2)',
      3: 'var(--e-3)',
    },
    fontFamily: {
      display: 'var(--f-display)',
      ui: 'var(--f-ui)',
      compiler: 'var(--f-compiler)',
    },
    extend: {
      transitionDuration: { fast: 'var(--d-fast)', base: 'var(--d-base)', slow: 'var(--d-slow)' },
      transitionTimingFunction: { settle: 'var(--ease-settle)', out: 'var(--ease-out)' },
      maxWidth: { measure: 'var(--measure)' },
    },
  },
  plugins: [],
};
