#!/usr/bin/env bash
#
# Grants each Cloud Run service account read access to exactly the secrets its service
# declares -- and nothing else. The worker has no reason to read the voice key, and this
# is where that stops being a matter of trust.
#
# Generated by scripts/gen-secret-artifacts.mjs. Edit the inventory, not this file.
#
# Usage: PROJECT_ID=your-project ./infra/iam.sh

set -euo pipefail

: "${PROJECT_ID:?set PROJECT_ID}"

SA_API="kc-api@${PROJECT_ID}.iam.gserviceaccount.com"
SA_WORKER="kc-worker@${PROJECT_ID}.iam.gserviceaccount.com"

# --- Service accounts ---
gcloud iam service-accounts create kc-api --project="$PROJECT_ID" \
  --display-name="Kitchen Compiler api" || true
gcloud iam service-accounts create kc-worker --project="$PROJECT_ID" \
  --display-name="Kitchen Compiler worker" || true

# --- Secrets ---
# DATABASE_URL: Postgres connection string, including credentials.
gcloud secrets create DATABASE_URL --project="$PROJECT_ID" --replication-policy=automatic || true
gcloud secrets add-iam-policy-binding DATABASE_URL --project="$PROJECT_ID" \
  --member="serviceAccount:${SA_API}" --role="roles/secretmanager.secretAccessor"
gcloud secrets add-iam-policy-binding DATABASE_URL --project="$PROJECT_ID" \
  --member="serviceAccount:${SA_WORKER}" --role="roles/secretmanager.secretAccessor"

# REDIS_URL: Redis connection string for cache, queue and pub/sub.
gcloud secrets create REDIS_URL --project="$PROJECT_ID" --replication-policy=automatic || true
gcloud secrets add-iam-policy-binding REDIS_URL --project="$PROJECT_ID" \
  --member="serviceAccount:${SA_API}" --role="roles/secretmanager.secretAccessor"
gcloud secrets add-iam-policy-binding REDIS_URL --project="$PROJECT_ID" \
  --member="serviceAccount:${SA_WORKER}" --role="roles/secretmanager.secretAccessor"

# JWT_SECRET: Signing key for anonymous device tokens.
gcloud secrets create JWT_SECRET --project="$PROJECT_ID" --replication-policy=automatic || true
gcloud secrets add-iam-policy-binding JWT_SECRET --project="$PROJECT_ID" \
  --member="serviceAccount:${SA_API}" --role="roles/secretmanager.secretAccessor"

# BRAVE_API_KEY: Brave Search, for external recipe discovery. Discovery degrades without it.
gcloud secrets create BRAVE_API_KEY --project="$PROJECT_ID" --replication-policy=automatic || true
gcloud secrets add-iam-policy-binding BRAVE_API_KEY --project="$PROJECT_ID" \
  --member="serviceAccount:${SA_API}" --role="roles/secretmanager.secretAccessor"

# ELEVENLABS_API_KEY: Voice I/O. Requires convai_write. Voice degrades to text without it.
gcloud secrets create ELEVENLABS_API_KEY --project="$PROJECT_ID" --replication-policy=automatic || true
gcloud secrets add-iam-policy-binding ELEVENLABS_API_KEY --project="$PROJECT_ID" \
  --member="serviceAccount:${SA_API}" --role="roles/secretmanager.secretAccessor"

# SPOONACULAR_API_KEY: Optional idea source only. Never persisted to the corpus; 1 hour TTL.
gcloud secrets create SPOONACULAR_API_KEY --project="$PROJECT_ID" --replication-policy=automatic || true
gcloud secrets add-iam-policy-binding SPOONACULAR_API_KEY --project="$PROJECT_ID" \
  --member="serviceAccount:${SA_API}" --role="roles/secretmanager.secretAccessor"

# SENTRY_DSN_SERVER: Server-side error reporting. The client DSN is public and lives elsewhere.
gcloud secrets create SENTRY_DSN_SERVER --project="$PROJECT_ID" --replication-policy=automatic || true
gcloud secrets add-iam-policy-binding SENTRY_DSN_SERVER --project="$PROJECT_ID" \
  --member="serviceAccount:${SA_API}" --role="roles/secretmanager.secretAccessor"
gcloud secrets add-iam-policy-binding SENTRY_DSN_SERVER --project="$PROJECT_ID" \
  --member="serviceAccount:${SA_WORKER}" --role="roles/secretmanager.secretAccessor"

# --- Vertex AI: no secret, just the role. ---
gcloud projects add-iam-policy-binding "$PROJECT_ID" \
  --member="serviceAccount:${SA_API}" --role="roles/aiplatform.user"
gcloud projects add-iam-policy-binding "$PROJECT_ID" \
  --member="serviceAccount:${SA_WORKER}" --role="roles/aiplatform.user"

echo "IAM configured. Mount every secret by an explicit version number, never the"
echo "floating alias -- rotation should be a deploy you can see and roll back:"
echo "  gcloud run deploy api --update-secrets=BRAVE_API_KEY=BRAVE_API_KEY:7"
